# permissions for end users to view logicalclusters.
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRole
metadata:
  name: logicalcluster-viewer-role
rules:
- apiGroups:
  - scheduler-mgr.ucloud.cn
  resources:
  - logicalclusters
  verbs:
  - get
  - list
  - watch
- apiGroups:
  - scheduler-mgr.ucloud.cn
  resources:
  - logicalclusters/status
  verbs:
  - get
